"""
This package contains modules which provide functionality for AST transformations

==========
Submodules
==========
* :py:mod:`.transformer_visitor`:     Helper class to construct high-level abstract proof circuits
* :py:mod:`.internal_call_transformer`:     Helper class to construct high-level abstract proof circuits
* :py:mod:`.circuit_constraints` Defines the different types of abstract circuit statements
* :py:mod:`.circuit_generator`   Compiles abstract proof circuits generated by circuit_helper into concrete proof circuits and generates verification contracts
"""