"""
This module provides classes to deal with proof circuits

circuit_helper.py:      Helper class to construct high-level abstract proof circuits
circuit_constraints.py: Defines the different types of abstract circuit statements
circuit_generator.py:   Compiles abstract proof circuits generated by circuit_helper into concrete proof circuits
                        and generates verification contracts
/backends:              CircuitGenerator implementations for different NIZK backends (for now just jsnark)
"""