"""
This package contains modules which provide functionality to deal with proof circuits

==========
Submodules
==========
* :py:mod:`.circuit_helper`:     Helper class to construct high-level abstract proof circuits
* :py:mod:`.circuit_constraints` Defines the different types of abstract circuit statements
* :py:mod:`.circuit_generator`   Compiles abstract proof circuits generated by circuit_helper into concrete proof circuits and generates verification contracts

===========
Subpackages
===========
* :py:mod:`.backends`:           CircuitGenerator implementations for different NIZK backends (for now just jsnark)
"""