from typing import Optional

from zkay.zkay_ast.ast import TypeName, HybridArgType, Expression, HybridArgumentIdf


class BaseNameFactory:
    """A Base name factory can generate fresh, unused name strings with a given prefix"""

    def __init__(self, base_name: str):
        self.base_name = base_name
        self.count = 0

    def get_new_name(self, t: TypeName, inc=False) -> str:
        """
        Generate a fresh name for a value of type t.

        :param t: transformed type
        :param inc: if True, the internal counter, which is used as part of fresh ids, is incremented
        """
        if t.is_key():
            postfix = 'key'
        elif t.is_cipher():
            postfix = 'cipher'
        elif t.is_randomness():
            postfix = 'rnd'
        else:
            postfix = 'plain'
        name = f'{self.base_name}{self.count}_{postfix}'
        if inc:
            self.count += 1
        return name


class NameFactory(BaseNameFactory):
    """A Name factory can generate fresh, unused HybridArgumentIdfs with a given prefix."""

    def __init__(self, base_name: str, arg_type: HybridArgType):
        super().__init__(base_name)
        self.arg_type = arg_type
        self.size = 0
        self.idfs = []

    def get_new_idf(self, t: TypeName, priv_expr: Optional[Expression] = None) -> HybridArgumentIdf:
        """Generate a new HybridArgumentIdf which references priv_expr and has transformed type t."""
        name = self.get_new_name(t, inc=True)
        idf = HybridArgumentIdf(name, t, self.arg_type, priv_expr)
        self.size += t.size_in_uints
        self.idfs.append(idf)
        return idf

    def add_idf(self, name: str, t: TypeName, priv_expr: Optional[Expression] = None):
        """
        Generate a new HybridArgumentIdf with the given name.

        This also adds the HybridArgumentIdf to the internal list of identifiers generated by this NameFactory.
        """
        idf = HybridArgumentIdf(name, t, self.arg_type, priv_expr)
        self.count += 1
        self.size += t.size_in_uints
        self.idfs.append(idf)
        return idf
