class Manifest:
    uuid = 'uuid'
    project_dir = 'project-dir'
    zkay_version = 'zkay-version'
    solc_version = 'solc-version'
    zkay_contract_filename = 'zkay-contract-file'
    contract_filename = 'contract-file'
    proving_scheme = 'proving-scheme'
    pki_lib = 'pki-lib'
    verify_lib = 'verify-lib'
    verifier_names = 'verifier-names'
